baseURL = "https://peyman.blog/sql/"
languageCode = "en-us"
title = "SQL by example"
themesDir = "themes"
theme = "blueberry"

RelativeURLs = true
CanonifyURLs = true

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = false
PygmentsStyle = "nord"
paginate = 30

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@_peymanslh"
  showAuthorOnHomepage = false
  showAuthorOnPosts = false
  showPostsOnHomepage = true
  addFrame = false
  addDot = true

[taxonomies]
    tag = "tags"

copyright = "2023"
languageCode = "en-us"

[Author]
    name = "Peyman Salehi"
    email = "slh.peyman@gmail.com"
