version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=sbe
      - POSTGRES_PASSWORD=sqlbyexample
      - POSTGRES_DB=sbe
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
